[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate"

[deploy]
preDeployCommand = "npx prisma generate"
startCommand = "node src/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
